language: csharp
matrix:
  include:
    - os: linux
      dist: trusty
addons:
  chrome: stable
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

mono: 5.4.1
dotnet: 2.1.300
services:
  - docker

install:
  - nvm install 8.12.0
  - nvm use 8.12.0
  - yarn

branches:
  only:
    - master
    - dev
    
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./build.sh --target=ci ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then set -e ; tag=`date -u +%Y%m%d%H%M` ; export imagetag="jijiechen/dotnetclub:$tag" ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./build-linux.sh --target=ci --imagetag="$imagetag" ; ./codecov -f "test/Discussion.Web.Tests/coverage.opencover.xml" -t $CODECOV_TOKEN ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$DOCKER_USERNAME" != "" ]; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push $imagetag ; fi

cache:
  yarn: true
  directories:
  - /home/travis/.nuget/packages
