language: csharp
matrix:
  include:
    - os: linux
      dist: trusty
addons:
  chrome: stable
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

mono: 5.4.1
dotnet: 2.1.504
services:
  - docker

install:
  - nvm install 8.12.0
  - nvm use 8.12.0
  - yarn

branches:
  only:
    - master
    - dev

script:
  - tag=`date -u +%Y%m%d%H%M` ; export imagetag="jijiechen/dotnetclub:$tag"
  - ./build-linux.sh --target=ci --imagetag="$imagetag"
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$DOCKER_USERNAME" != "" ]; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push $imagetag ; fi

after_success:
  - ./codecov -f "./test/Discussion.Web.Tests/coverage.opencover.xml" -t $CODECOV_TOKEN
  - ./codecov -f "./test/Discussion.Admin.Tests/coverage.opencover.xml" -t $CODECOV_TOKEN
  - ./codecov -f "./src/Discussion.Admin/ClientApp/coverage/lcov.info" -t $CODECOV_TOKEN

cache:
  yarn: true
  directories:
  - /home/travis/.nuget/packages
