# How to run this image?
# 1. (optional) At (WorkDir), Create your appsettings.json or appsettings.<env>.json
# 2. (optional) At (WorkDir), Create your database file
# 3. execute docker run -d -v (WorkDir):/club-data -p 5000:5000 jijiechen/dotnetclub 



FROM microsoft/dotnet:2.1.4-runtime

ENV ASPNETCORE_URLS http://*:5000
VOLUME /club-data

COPY . /club-app

RUN useradd --uid 5000 --create-home --home /home/clubadm clubadm
RUN chown -R clubadm /home/clubadm
RUN chown -R clubadm /club-data

USER clubadm
WORKDIR /club-data
ENTRYPOINT ["dotnet", "/club-app/Discussion.Web.dll", "--webroot", "/club-app/wwwroot"]

