apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
spec:
  limits:
  - default:
      memory: 1Gi
      cpu: 1
    defaultRequest:
      memory: 256Mi
      cpu: 0.5
    type: Container