apiVersion: v1
kind: Secret
metadata:
  name: heketi-secret
  namespace: default
data:
  # base64 encoded password. E.g.: echo -n "mypassword" | base64
  key: SGVrZXRpQWRtaW4h   # 请将此值改为具体的正确的值
type: kubernetes.io/glusterfs

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://192.168.1.74:8080"       # 请将此值改为具体的正确的值
  clusterid: "df0c7eb0e3cee2ce7812dfaf534a3a3d"    # 请将此值改为具体的正确的值
  restauthenabled: "true"
  restuser: "admin"
  secretNamespace: "default"
  secretName: "heketi-secret"
  volumetype: "replicate:3"