apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-claim
  labels:
    name: web-claim
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany 
  storageClassName: fast     # 如果使用静态 PV，请注释此行
  resources:
    requests:
      storage: 1Gi