kind: Secret
apiVersion: v1
metadata:
  name: web-protection-keys
stringData:
  key-8ad278dc-ed4e-4ec1-b42d-d428be74982f.xml: |-
    <?xml version="1.0" encoding="utf-8"?>
    <key id="8ad278dc-ed4e-4ec1-b42d-d428be74982f" version="1">
      <creationDate>2019-03-22T03:34:57.168154Z</creationDate>
      <activationDate>2019-03-22T03:34:57.141955Z</activationDate>
      <expirationDate>2019-06-20T03:34:57.141955Z</expirationDate>
      <descriptor deserializerType="Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60">
        <descriptor>
          <encryption algorithm="AES_256_CBC" />
          <validation algorithm="HMACSHA256" />
          <masterKey p4:requiresEncryption="true" xmlns:p4="http://schemas.asp.net/2015/03/dataProtection">
            <!-- Warning: the key below is in an unencrypted form. -->
            <value>B5YU0BnFnG0CXQgQuj4vQelcEpaYuo6xRA9EZsju6MBjVp/HTPIFXsa8fcmH1H3JPiskHzkApQ/d94qfTAIJeg==</value>
          </masterKey>
        </descriptor>
      </descriptor>
    </key>