//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discussion.Web.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MvcModelBindingResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcModelBindingResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Discussion.Web.Resources.MvcModelBindingResource", typeof(MvcModelBindingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MissingBindRequiredValueAccessor {
            get {
                return ResourceManager.GetString("MissingBindRequiredValueAccessor", resourceCulture);
            }
        }
        
        public static string MissingKeyOrValueAccessor {
            get {
                return ResourceManager.GetString("MissingKeyOrValueAccessor", resourceCulture);
            }
        }
        
        public static string MissingRequestBodyRequiredValueAccessor {
            get {
                return ResourceManager.GetString("MissingRequestBodyRequiredValueAccessor", resourceCulture);
            }
        }
        
        public static string ValueMustNotBeNullAccessor {
            get {
                return ResourceManager.GetString("ValueMustNotBeNullAccessor", resourceCulture);
            }
        }
        
        public static string AttemptedValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("AttemptedValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        public static string NonPropertyAttemptedValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("NonPropertyAttemptedValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        public static string UnknownValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("UnknownValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        public static string NonPropertyUnknownValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("NonPropertyUnknownValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        public static string ValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("ValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        public static string ValueMustBeANumberAccessor {
            get {
                return ResourceManager.GetString("ValueMustBeANumberAccessor", resourceCulture);
            }
        }
        
        public static string NonPropertyValueMustBeANumberAccessor {
            get {
                return ResourceManager.GetString("NonPropertyValueMustBeANumberAccessor", resourceCulture);
            }
        }
    }
}
